<?php
require_once dirname(__FILE__) . '/../../PrestaTestBase.php';
require_once dirname(__FILE__) . '/../../../lib/util/Arr.php';

/**
 * Test class for Util_Arr.
 * Generated by PHPUnit on 2011-01-30 at 20:42:07.
 */
class Util_ArrTest extends PrestaTestBase {

    /**
     * @var Util_Arr
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Util_Arr;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
