<?php
require_once dirname(__FILE__) . '/../../PrestaTestBase.php';
require_once dirname(__FILE__) . '/../../../lib/presta/Requirements.php';

/**
 * Test class for Presta_Requirements.
 * Generated by PHPUnit on 2011-01-30 at 20:42:07.
 */
class Presta_RequirementsTest extends PrestaTestBase {

    /**
     * @var Presta_Requirements
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Presta_Requirements;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testCheck().
     */
    public function testCheck() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}